# Generated by Django 5.0.4 on 2024-05-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_logintable_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
